In [1]:
import pandas as pd
import numpy as np

#-----------------------------------------------------------------------------------------------------------------------------------------------

# 0.SERIES

In [58]:

fruits=pd.Series(('Apple','Bananan'))
number=pd.Series([1,2,3,4,5])

In [59]:
number

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [45]:
fruits

0      Apple
1    Bananan
dtype: str

#-----------------------------------------------------------------------------------------------------------------------------------------------

# 1.LIST DATAFRAME

In [51]:
apple=['apple',150]
banana=['banana','70']
fruits=[apple,banana]
df=pd.DataFrame(fruits)
df.columns=('name','price')
df

     name price
0   apple   150
1  banana    70

#-----------------------------------------------------------------------------------------------------------------------------------------------

# 2.TUPLE DATAFRAME

In [52]:
apple=('apple',150)
banana=('banana','70')
fruits=(apple,banana)
df=pd.DataFrame(fruits)
df.columns=('name','price')
df

     name price
0   apple   150
1  banana    70

#-----------------------------------------------------------------------------------------------------------------------------------------------

# 3.DICTIONARY DATAFRAME

In [55]:
apple={'name':'apple','price':'150'}
banana={'name':'banana','price':'70'}
df=pd.DataFrame(apple,banana)
df

        name price
name   apple   150
price  apple   150

# 3.1 DICTIONARIES OF LIST DATAFRAME

In [ ]:
#  SYNTAX:
#   {
#       "Column1": [value1, value2],
#       "Column2": [value1, value2]
#   }

data1={
    'NAME':['riyas','sameer'],
    'AGE':[20,33]
}
pd.DataFrame(data1)

     NAME  AGE
0   riyas   20
1  sameer   33

# 3.2 LIST OF DICTIONARIES DATAFRAME

In [13]:
#  SYNTAX:
#   [
#       {"Column1": value, "Column2": value},
#       {"Column1": value, "Column2": value}
#   ]



data2=[
    {'NAME':'riyas','AGE':20},
    {'NAME':'sameer','AGE':22}
]
pd.DataFrame(data2)

     NAME  AGE
0   riyas   20
1  sameer   22

# 3.3 LIST OF LISTS DATAFRAME

In [14]:
data3=[['riyas',20],['sameer',22]]
pd.DataFrame(data3,columns=['Name','AGE'])

     Name  AGE
0   riyas   20
1  sameer   22

# 3.4 NUMPY ARRAY DATAFRAME

In [ ]:
# NUMPY PACKAGE INSTALL
data4=np.array([['riyas',20],['sameer',22]])
pd.DataFrame(data4,columns=['Name','AGE'])

     Name AGE
0   riyas  20
1  sameer  22

# 3.5 DICTIONARY OF SERIES DATAFRAME

In [ ]:
# EACH COLUMN IS A SERIES
n=pd.Series(['riyas','sameer']) # SERIES 1
a=pd.Series([20,22]) # SERIES 2
pd.DataFrame(
    {
        'NAME':n,
        'AGE':a
    }
)

     NAME  AGE
0   riyas   20
1  sameer   22

#-----------------------------------------------------------------------------------------------------------------------------------------------

# 3.6 SERIES OBJECT

In [ ]:
# CONVERT ONE SERIES INTO A DATAFRRAME
m=pd.Series([90,67,45,67,67])
pd.DataFrame(m,columns=['MARKS'])

   MARKS
0     90
1     67
2     45
3     67
4     67

#-----------------------------------------------------------------------------------------------------------------------------------------------