In [5]:
import pandas as pd

#-----------------------------------------------------------------------------------------------------------------------------------------------

# 1.CLIPBOARD

In [ ]:
# clipbord read
df=pd.read_clipboard()
df

,0,Chevrolet Chevelle Malibu,18.0,8.0,307.0,130.0,3504,12.0,70,US
0,1,Buick Skylark 320,15.0,8.0,350.0,165.0,3693,11.5,70,US
1,2,Plymouth Satellite,18.0,8.0,318.0,150.0,3436,NaN,70,US
2,3,AMC Rebel SST,16.0,8.0,304.0,150.0,3433,12.0,70,US
3,4,Ford Torino,17.0,8.0,302.0,140.0,3449,10.5,70,US
4,...,...,...,...,...,...,...,...,...,...
5,401,Ford Mustang GL,27.0,4.0,140.0,86.0,2790,15.6,82,US
6,402,Volkswagen Pickup,44.0,4.0,97.0,52.0,2130,24.6,82,Europe
7,403,Dodge Rampage,32.0,4.0,135.0,84.0,2295,11.6,82,US
8,404,Ford Ranger,28.0,4.0,120.0,79.0,2625,18.6,82,US
9,405,Chevy S-10,31.0,4.0,119.0,82.0,2720,19.4,82,US

#-----------------------------------------------------------------------------------------------------------------------------------------------

# 2.READ EXCEL FILE

In [7]:
# read excel file must install package in openpyxl
!pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\riyas\appdata\local\programs\python\python312\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\riyas\appdata\local\programs\python\python312\lib\site-packages (from openpyxl) (2.0.0)

WARNING: There was an error checking the latest version of pip.

In [6]:
#read excel file and choose header
df=pd.read_excel('data/cars.xlsx',header=1)
df

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin
0,STRING,DOUBLE,INT,DOUBLE,DOUBLE,DOUBLE,DOUBLE,INT,CAT
1,Chevrolet Chevelle Malibu,18,8,307,130,3504,12,70,US
2,Buick Skylark 320,15,8,350,165,3693,11.5,70,US
3,Plymouth Satellite,18,8,318,150,3436,NaN,70,US
4,AMC Rebel SST,16,8,304,150,3433,12,70,US
...,...,...,...,...,...,...,...,...,...
402,Ford Mustang GL,27,4,140,86,2790,15.6,82,US
403,Volkswagen Pickup,44,4,97,52,2130,24.6,82,Europe
404,Dodge Rampage,32,4,135,84,2295,11.6,82,US
405,Ford Ranger,28,4,120,79,2625,18.6,82,US
406,Chevy S-10,31,4,119,82,2720,19.4,82,US

In [ ]:
# sheetname change
df=pd.read_excel('data/cars.xlsx',header=1,sheet_name='Summary')
df

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin
0,Ford Pinto,18,6,171,97,2984,14.5,75,US
1,Volkswagen Rabbit,29,4,90,70,1937,14.0,75,Europe
2,AMC Pacer,19,6,232,90,3211,17.0,75,US
3,Audi 100LS,23,4,115,95,2694,15.0,75,Europe
4,Peugeot 504,23,4,120,88,2957,17.0,75,Europe
5,Volvo 244DL,22,4,121,98,2945,14.5,75,Europe
6,Saab 99LE,25,4,121,115,2671,13.5,75,Europe
7,Honda Civic CVCC,33,4,91,53,1795,17.5,75,Japan
8,Fiat 131,28,4,107,86,2464,15.5,76,Europe

#-----------------------------------------------------------------------------------------------------------------------------------------------

# 3. READ JSON FILE

In [12]:
#read json file
df=pd.read_json('data/cars.json')
df

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin
0,STRING,DOUBLE,INT,DOUBLE,DOUBLE,DOUBLE,DOUBLE,INT,CAT
1,riyas,18,8,307,130,3504,12,70,US
2,Buick Skylark 320,15,8,350,165,3693,11.5,70,US
3,Plymouth Satellite,18,8,318,150,3436,,70,US
4,AMC Rebel SST,16,8,304,150,3433,12,70,US
...,...,...,...,...,...,...,...,...,...
402,Ford Mustang GL,27,4,140,86,2790,15.6,82,US
403,Volkswagen Pickup,44,4,97,52,2130,24.6,82,Europe
404,Dodge Rampage,32,4,135,84,2295,11.6,82,US
405,Ford Ranger,28,4,120,79,2625,18.6,82,US
406,Chevy S-10,31,4,119,82,2720,19.4,82,US

#-----------------------------------------------------------------------------------------------------------------------------------------------

# 4. READ PICKLE FILE

In [ ]:
#read pickle file
df=pd.read_pickle('data/cars.pk')
df

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin
0,STRING,DOUBLE,INT,DOUBLE,DOUBLE,DOUBLE,DOUBLE,INT,CAT
1,Chevrolet Chevelle Malibu,18,8,307,130,3504,12,70,US
2,Buick Skylark 320,15,8,350,165,3693,11.5,70,US
3,Plymouth Satellite,18,8,318,150,3436,,70,US
4,AMC Rebel SST,16,8,304,150,3433,12,70,US
...,...,...,...,...,...,...,...,...,...
402,Ford Mustang GL,27,4,140,86,2790,15.6,82,US
403,Volkswagen Pickup,44,4,97,52,2130,24.6,82,Europe
404,Dodge Rampage,32,4,135,84,2295,11.6,82,US
405,Ford Ranger,28,4,120,79,2625,18.6,82,US
406,Chevy S-10,31,4,119,82,2720,19.4,82,US

#-----------------------------------------------------------------------------------------------------------------------------------------------