In [2]:
import pandas as pd

In [3]:
#read csv data
df=pd.read_csv('data/cars.csv')
df

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin
0,Chevrolet Chevelle Malibu,18.0,8.0,307.0,130.0,3504,12.0,70,US
1,Buick Skylark 320,15.0,8.0,350.0,165.0,3693,11.5,70,US
2,Plymouth Satellite,18.0,8.0,318.0,150.0,3436,NaN,70,US
3,AMC Rebel SST,16.0,8.0,304.0,150.0,3433,12.0,70,US
4,Ford Torino,17.0,8.0,302.0,140.0,3449,10.5,70,US
...,...,...,...,...,...,...,...,...,...
401,Ford Mustang GL,27.0,4.0,140.0,86.0,2790,15.6,82,US
402,Volkswagen Pickup,44.0,4.0,97.0,52.0,2130,24.6,82,Europe
403,Dodge Rampage,32.0,4.0,135.0,84.0,2295,11.6,82,US
404,Ford Ranger,28.0,4.0,120.0,79.0,2625,18.6,82,US
405,Chevy S-10,31.0,4.0,119.0,82.0,2720,19.4,82,US

# 1.DOT NOTATION

In [ ]:
# . Noataion
df.Car

0      Chevrolet Chevelle Malibu
1              Buick Skylark 320
2             Plymouth Satellite
3                  AMC Rebel SST
4                    Ford Torino
                 ...
401              Ford Mustang GL
402            Volkswagen Pickup
403                Dodge Rampage
404                  Ford Ranger
405                   Chevy S-10
Name: Car, Length: 406, dtype: str

# 2. BRACKET METHOD

In [ ]:
# Bracket method
df['Car']

0      Chevrolet Chevelle Malibu
1              Buick Skylark 320
2             Plymouth Satellite
3                  AMC Rebel SST
4                    Ford Torino
                 ...
401              Ford Mustang GL
402            Volkswagen Pickup
403                Dodge Rampage
404                  Ford Ranger
405                   Chevy S-10
Name: Car, Length: 406, dtype: str

# 2.1 BRACKET METHOD N COLUMNS

In [ ]:
# Bracket method more than column
df[['Car','MPG']]

                           Car   MPG
0    Chevrolet Chevelle Malibu  18.0
1            Buick Skylark 320  15.0
2           Plymouth Satellite  18.0
3                AMC Rebel SST  16.0
4                  Ford Torino  17.0
..                         ...   ...
401            Ford Mustang GL  27.0
402          Volkswagen Pickup  44.0
403              Dodge Rampage  32.0
404                Ford Ranger  28.0
405                 Chevy S-10  31.0

[406 rows x 2 columns]

# 2.2 N COLUMNS TO WRITE CSV FILE

In [ ]:
#retrive collumn wite csv file
df[['Car','MPG']].to_csv('carsss.csv')

# 3. GET METHOD

In [7]:
# GET Method 
df.get(['Car'])

                           Car
0    Chevrolet Chevelle Malibu
1            Buick Skylark 320
2           Plymouth Satellite
3                AMC Rebel SST
4                  Ford Torino
..                         ...
401            Ford Mustang GL
402          Volkswagen Pickup
403              Dodge Rampage
404                Ford Ranger
405                 Chevy S-10

[406 rows x 1 columns]

# 4. CHECK HOW MANY ROWS RECORDS ONLY

In [ ]:
#index --> rows record 
df.index

RangeIndex(start=0, stop=406, step=1)

# 5. CHECK HOW MANY COLUMNS RECORDS ONLY

In [ ]:
#column --> column record
df.columns

Index(['Car', 'MPG', 'Cylinders', 'Displacement', 'Horsepower', 'Weight',
       'Acceleration', 'Model', 'Origin'],
      dtype='str')

# 6. CHECK COLUMNS DATA TYPES

In [ ]:
#column data types
df.dtypes

Car                 str
MPG             float64
Cylinders       float64
Displacement    float64
Horsepower      float64
Weight            int64
Acceleration    float64
Model             int64
Origin              str
dtype: object

# 6.1 CHECK PARTICUALAR COLUMN DATA TYPE

In [ ]:
#specific column data types
df['Car'].dtypes

# 7. MISSING VALUES IDENTIFIED

In [ ]:
# Missing values detialed information like 404,405 NOT FOUND
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 406 entries, 0 to 405
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Car           406 non-null    str
 1   MPG           406 non-null    float64
 2   Cylinders     405 non-null    float64
 3   Displacement  406 non-null    float64
 4   Horsepower    404 non-null    float64
 5   Weight        406 non-null    int64
 6   Acceleration  405 non-null    float64
 7   Model         406 non-null    int64
 8   Origin        406 non-null    str
dtypes: float64(5), int64(2), str(2)
memory usage: 28.7 KB

# 8. RETRIVE VALUES

In [ ]:
#Data values access
df.values

array([['Chevrolet Chevelle Malibu', 18.0, 8.0, ..., 12.0, 70, 'US'],
       ['Buick Skylark 320', 15.0, 8.0, ..., 11.5, 70, 'US'],
       ['Plymouth Satellite', 18.0, 8.0, ..., nan, 70, 'US'],
       ...,
       ['Dodge Rampage', 32.0, 4.0, ..., 11.6, 82, 'US'],
       ['Ford Ranger', 28.0, 4.0, ..., 18.6, 82, 'US'],
       ['Chevy S-10', 31.0, 4.0, ..., 19.4, 82, 'US']],
      shape=(406, 9), dtype=object)

# 9. RETRIVE PARTICULAR COLUMNS VALUES

In [ ]:
#Data values acess with particualr column
df['Car'].values

<StringArray>
[ 'Chevrolet Chevelle Malibu',          'Buick Skylark 320',
         'Plymouth Satellite',              'AMC Rebel SST',
                'Ford Torino',           'Ford Galaxie 500',
           'Chevrolet Impala',          'Plymouth Fury iii',
           'Pontiac Catalina',         'AMC Ambassador DPL',
 ...
 'Chrysler Lebaron Medallion',             'Ford Grenada l',
           'Toyota Celica GT',          'Dodge Charger 2.2',
           'Chevrolet Camaro',            'Ford Mustang GL',
          'Volkswagen Pickup',              'Dodge Rampage',
                'Ford Ranger',                 'Chevy S-10']
Length: 406, dtype: str

# 10. ROWS AND COLUMNS DETAILS

In [10]:
#range and columns name [0,1] --> acess particular data
df.axes

[RangeIndex(start=0, stop=406, step=1),
 Index(['Car', 'MPG', 'Cylinders', 'Displacement', 'Horsepower', 'Weight',
        'Acceleration', 'Model', 'Origin'],
       dtype='str')]

# 11.DIMENSIONAL HOW MANY ROWS AND COLUMNS

In [13]:
#dimensional like x axis, y axis Ex:--> a['Car].ndim=>1
df.ndim

2

# 12. ROWS X COLUMNS

In [ ]:
# rows X colum -- 409 x 9
df.size

3654

# 13. ROWS & COLUMNS

In [ ]:
#How many rows and columns  Ex:---> a.shape[0,1]
df.shape

(406, 9)

# 14. MEMORY OCCUPIED CHECK

In [ ]:
# memeory_usage -->overall occupied data , (deep=True)-->Exact occupied data
df.memory_usage(deep=True)

Index             132
Car             26526
MPG              3248
Cylinders        3248
Displacement     3248
Horsepower       3248
Weight           3248
Acceleration     3248
Model            3248
Origin          21235
dtype: int64

# 15. FIRST 4 DATA

In [5]:
#first 4 rows , customize -->a.head(28)
df.head()

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin
0,Chevrolet Chevelle Malibu,18.0,8.0,307.0,130.0,3504,12.0,70,US
1,Buick Skylark 320,15.0,8.0,350.0,165.0,3693,11.5,70,US
2,Plymouth Satellite,18.0,8.0,318.0,150.0,3436,NaN,70,US
3,AMC Rebel SST,16.0,8.0,304.0,150.0,3433,12.0,70,US
4,Ford Torino,17.0,8.0,302.0,140.0,3449,10.5,70,US

# 15.1 LASR 4 DATA

In [ ]:
#last four rows , customize --> a.tail(30)
df.tail()

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin
401,Ford Mustang GL,27.0,4.0,140.0,86.0,2790,15.6,82,US
402,Volkswagen Pickup,44.0,4.0,97.0,52.0,2130,24.6,82,Europe
403,Dodge Rampage,32.0,4.0,135.0,84.0,2295,11.6,82,US
404,Ford Ranger,28.0,4.0,120.0,79.0,2625,18.6,82,US
405,Chevy S-10,31.0,4.0,119.0,82.0,2720,19.4,82,US