In [1]:
import pandas as pd

#-----------------------------------------------------------------------------------------------------------------------------------------------

# CREATE DATARAME

In [11]:
df=pd.DataFrame(
    {
        'Name':['riyas','sameer','vajith','sarbu','rijas'],
        'Age':[20,20,25,24,21],
        'work':['Analytics Engineer','Store Manager','Technical Support','Product Manager','Video Editor']
    }
)
df

     Name  Age                work
0   riyas   20  Analytics Engineer
1  sameer   20       Store Manager
2  vajith   25   Technical Support
3   sarbu   24     Product Manager
4   rijas   21        Video Editor

#-----------------------------------------------------------------------------------------------------------------------------------------------

# 1. COPY DATAFRAME

In [6]:
df2=df.copy()
df2

     Name  Age                work
0   riyas   20  Analytics Engineer
1  sameer   20       Store Manager
2  vajith   25   Technical Support
3   sarbu   24     Product Manager
4   rijas   21        Video Editor

# 1.2 CHANGE COPY COLUMNS

In [8]:
df2.columns=['person','old','profess']
df2

   person  old             profess
0   riyas   20  Analytics Engineer
1  sameer   20       Store Manager
2  vajith   25   Technical Support
3   sarbu   24     Product Manager
4   rijas   21        Video Editor

# 1.3 CHECK CHANGES IN ORIGINAL

In [9]:
df

     Name  Age                work
0   riyas   20  Analytics Engineer
1  sameer   20       Store Manager
2  vajith   25   Technical Support
3   sarbu   24     Product Manager
4   rijas   21        Video Editor

#-----------------------------------------------------------------------------------------------------------------------------------------------

# 2. REFERANCE DATAFRAME

In [12]:
df_ref = df

# 2.1 CHANGE REFERANCE COLUMNS

In [14]:
df_ref.columns=['person','old','profess']
df_ref

   person  old             profess
0   riyas   20  Analytics Engineer
1  sameer   20       Store Manager
2  vajith   25   Technical Support
3   sarbu   24     Product Manager
4   rijas   21        Video Editor

# 2.2 CHECK CHANGES IN ORIGINAL

In [17]:
df

   person  old             profess
0   riyas   20  Analytics Engineer
1  sameer   20       Store Manager
2  vajith   25   Technical Support
3   sarbu   24     Product Manager
4   rijas   21        Video Editor

#-----------------------------------------------------------------------------------------------------------------------------------------------