In [1]:
import pandas as pd

In [4]:
df=pd.read_csv('dataset/Cars.csv')
df

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin
0,Chevrolet Chevelle Malibu,18.0,8.0,307.0,130.0,3504,12.0,70,US
1,Buick Skylark 320,15.0,8.0,350.0,165.0,3693,11.5,70,US
2,Plymouth Satellite,18.0,8.0,318.0,150.0,3436,NaN,70,US
3,AMC Rebel SST,16.0,8.0,304.0,150.0,3433,12.0,70,US
4,Ford Torino,17.0,8.0,302.0,140.0,3449,10.5,70,US
...,...,...,...,...,...,...,...,...,...
401,Ford Mustang GL,27.0,4.0,140.0,86.0,2790,15.6,82,US
402,Volkswagen Pickup,44.0,4.0,97.0,52.0,2130,24.6,82,Europe
403,Dodge Rampage,32.0,4.0,135.0,84.0,2295,11.6,82,US
404,Ford Ranger,28.0,4.0,120.0,79.0,2625,18.6,82,US
405,Chevy S-10,31.0,4.0,119.0,82.0,2720,19.4,82,US

# 1.SET [CAR] COLUMNS INDEX

In [6]:
df.set_index('Car')

,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin
Car,,,,,,,,
Chevrolet Chevelle Malibu,18.0,8.0,307.0,130.0,3504,12.0,70,US
Buick Skylark 320,15.0,8.0,350.0,165.0,3693,11.5,70,US
Plymouth Satellite,18.0,8.0,318.0,150.0,3436,NaN,70,US
AMC Rebel SST,16.0,8.0,304.0,150.0,3433,12.0,70,US
Ford Torino,17.0,8.0,302.0,140.0,3449,10.5,70,US
...,...,...,...,...,...,...,...,...
Ford Mustang GL,27.0,4.0,140.0,86.0,2790,15.6,82,US
Volkswagen Pickup,44.0,4.0,97.0,52.0,2130,24.6,82,Europe
Dodge Rampage,32.0,4.0,135.0,84.0,2295,11.6,82,US
Ford Ranger,28.0,4.0,120.0,79.0,2625,18.6,82,US
Chevy S-10,31.0,4.0,119.0,82.0,2720,19.4,82,US

# 2. CUSTOM COLUMN ORDER CHANGE

In [7]:
df.reindex(columns=['Origin','Car','Horsepower'])

     Origin                        Car  Horsepower
0        US  Chevrolet Chevelle Malibu       130.0
1        US          Buick Skylark 320       165.0
2        US         Plymouth Satellite       150.0
3        US              AMC Rebel SST       150.0
4        US                Ford Torino       140.0
..      ...                        ...         ...
401      US            Ford Mustang GL        86.0
402  Europe          Volkswagen Pickup        52.0
403      US              Dodge Rampage        84.0
404      US                Ford Ranger        79.0
405      US                 Chevy S-10        82.0

[406 rows x 3 columns]

# 2.1 CUSTOM INDEX ORDER CHANGE

In [8]:
df.reindex([1,3,5])

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin
1,Buick Skylark 320,15.0,8.0,350.0,165.0,3693,11.5,70,US
3,AMC Rebel SST,16.0,8.0,304.0,150.0,3433,12.0,70,US
5,Ford Galaxie 500,15.0,8.0,429.0,198.0,4341,10.0,70,US

# 2.2 CUSTOM INDEX ORDER CHANGE IN SET INDEX

In [ ]:
#  RULE ---> SET COLUMN INDEX THEN REINDEX INDEX COLUMN
df.reindex(['Chevy S-10', 'Ford Ranger'])

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin
Chevy S-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Ford Ranger,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# 3.ORDER CHANGED COLUMN OR INDEX SET (NEW INDEX)

In [12]:
df.reset_index()
df.reset_index(drop=True)

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin
0,Chevrolet Chevelle Malibu,18.0,8.0,307.0,130.0,3504,12.0,70,US
1,Buick Skylark 320,15.0,8.0,350.0,165.0,3693,11.5,70,US
2,Plymouth Satellite,18.0,8.0,318.0,150.0,3436,NaN,70,US
3,AMC Rebel SST,16.0,8.0,304.0,150.0,3433,12.0,70,US
4,Ford Torino,17.0,8.0,302.0,140.0,3449,10.5,70,US
...,...,...,...,...,...,...,...,...,...
401,Ford Mustang GL,27.0,4.0,140.0,86.0,2790,15.6,82,US
402,Volkswagen Pickup,44.0,4.0,97.0,52.0,2130,24.6,82,Europe
403,Dodge Rampage,32.0,4.0,135.0,84.0,2295,11.6,82,US
404,Ford Ranger,28.0,4.0,120.0,79.0,2625,18.6,82,US
405,Chevy S-10,31.0,4.0,119.0,82.0,2720,19.4,82,US