In [1]:
import pandas as pd

In [22]:
df=pd.read_csv('Dataset/cars.csv')
df

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin
0,Chevrolet Chevelle Malibu,18.0,8.0,307.0,130.0,3504,12.0,70,US
1,Buick Skylark 320,15.0,8.0,350.0,165.0,3693,11.5,70,US
2,Plymouth Satellite,18.0,8.0,318.0,150.0,3436,NaN,70,US
3,AMC Rebel SST,16.0,8.0,304.0,150.0,3433,12.0,70,US
4,Ford Torino,17.0,8.0,302.0,140.0,3449,10.5,70,US
...,...,...,...,...,...,...,...,...,...
401,Ford Mustang GL,27.0,4.0,140.0,86.0,2790,15.6,82,US
402,Volkswagen Pickup,44.0,4.0,97.0,52.0,2130,24.6,82,Europe
403,Dodge Rampage,32.0,4.0,135.0,84.0,2295,11.6,82,US
404,Ford Ranger,28.0,4.0,120.0,79.0,2625,18.6,82,US
405,Chevy S-10,31.0,4.0,119.0,82.0,2720,19.4,82,US

# 1. GET ROW VALUES

In [4]:
# GET ROW VALUES
df.loc[0]

Car             Chevrolet Chevelle Malibu
MPG                                  18.0
Cylinders                             8.0
Displacement                        307.0
Horsepower                          130.0
Weight                               3504
Acceleration                         12.0
Model                                  70
Origin                                 US
Name: 0, dtype: object

# 1.1 SET ROW VALUES

In [7]:
# SET ROW VALUES
df.loc[0]=['row_changed',1.1,1.1,1.1,1.1,1,1.1,1,'row_changed']
df

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin
0,row_changed,1.1,1.1,1.1,1.1,1,1.1,1,row_changed
1,Buick Skylark 320,15.0,8.0,350.0,165.0,3693,11.5,70,US
2,Plymouth Satellite,18.0,8.0,318.0,150.0,3436,NaN,70,US
3,AMC Rebel SST,16.0,8.0,304.0,150.0,3433,12.0,70,US
4,Ford Torino,17.0,8.0,302.0,140.0,3449,10.5,70,US
...,...,...,...,...,...,...,...,...,...
401,Ford Mustang GL,27.0,4.0,140.0,86.0,2790,15.6,82,US
402,Volkswagen Pickup,44.0,4.0,97.0,52.0,2130,24.6,82,Europe
403,Dodge Rampage,32.0,4.0,135.0,84.0,2295,11.6,82,US
404,Ford Ranger,28.0,4.0,120.0,79.0,2625,18.6,82,US
405,Chevy S-10,31.0,4.0,119.0,82.0,2720,19.4,82,US

# 2. GET ROW VALUES IN RANGE [ : ]

In [14]:
# GET ROW **RANGE VALUES 
df.loc[0:5]

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin
0,Chevrolet Chevelle Malibu,18.0,8.0,307.0,130.0,3504,12.0,70,US
1,Buick Skylark 320,15.0,8.0,350.0,165.0,3693,11.5,70,US
2,Plymouth Satellite,18.0,8.0,318.0,150.0,3436,NaN,70,US
3,AMC Rebel SST,16.0,8.0,304.0,150.0,3433,12.0,70,US
4,Ford Torino,17.0,8.0,302.0,140.0,3449,10.5,70,US
5,Ford Galaxie 500,15.0,8.0,429.0,198.0,4341,10.0,70,US

# 2.1 SET ROW VALUES IN RANGE [ : ]

In [17]:
# SET ROW **RANGE VALUES 
df.loc[0:5]=['range_changed',1.0,1.0,1.0,1.0,1,1.0,1,'range_changed']

# 2.3 CHECK CHANGES

In [20]:
df.loc[0:5]

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin
0,range_changed,1.0,1.0,1.0,1.0,1,1.0,1,range_changed
1,range_changed,1.0,1.0,1.0,1.0,1,1.0,1,range_changed
2,range_changed,1.0,1.0,1.0,1.0,1,1.0,1,range_changed
3,range_changed,1.0,1.0,1.0,1.0,1,1.0,1,range_changed
4,range_changed,1.0,1.0,1.0,1.0,1,1.0,1,range_changed
5,range_changed,1.0,1.0,1.0,1.0,1,1.0,1,range_changed

# 3. GET INTERMITTENT ROW VALUES

In [23]:
df.loc[[1,2,3]]

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin
1,Buick Skylark 320,15.0,8.0,350.0,165.0,3693,11.5,70,US
2,Plymouth Satellite,18.0,8.0,318.0,150.0,3436,NaN,70,US
3,AMC Rebel SST,16.0,8.0,304.0,150.0,3433,12.0,70,US

# 3.1 SET INTERMITTENT ROW VALUES

In [24]:
# SET INTERMITENT ROW VALUES
df.loc[[1,2,3]]=['intermitent_row',2.0,2.0,2.0,2.0,2,2.0,2,'intermitent_row']

# 3.2 CHECK CHANGES

In [26]:
df.loc[1:3]

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin
1,intermitent_row,2.0,2.0,2.0,2.0,2,2.0,2,intermitent_row
2,intermitent_row,2.0,2.0,2.0,2.0,2,2.0,2,intermitent_row
3,intermitent_row,2.0,2.0,2.0,2.0,2,2.0,2,intermitent_row