In [1]:
import pandas as pd

In [12]:
df=pd.read_csv('Dataset/cars.csv')
df

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin
0,Chevrolet Chevelle Malibu,18.0,8.0,307.0,130.0,3504,12.0,70,US
1,Buick Skylark 320,15.0,8.0,350.0,165.0,3693,11.5,70,US
2,Plymouth Satellite,18.0,8.0,318.0,150.0,3436,NaN,70,US
3,AMC Rebel SST,16.0,8.0,304.0,150.0,3433,12.0,70,US
4,Ford Torino,17.0,8.0,302.0,140.0,3449,10.5,70,US
...,...,...,...,...,...,...,...,...,...
401,Ford Mustang GL,27.0,4.0,140.0,86.0,2790,15.6,82,US
402,Volkswagen Pickup,44.0,4.0,97.0,52.0,2130,24.6,82,Europe
403,Dodge Rampage,32.0,4.0,135.0,84.0,2295,11.6,82,US
404,Ford Ranger,28.0,4.0,120.0,79.0,2625,18.6,82,US
405,Chevy S-10,31.0,4.0,119.0,82.0,2720,19.4,82,US

## REMEMBER COLON [ : ] MAIN

# 1. GET COLUMN VALUES

In [6]:
# GET COLUMN VALUES
df.loc[:,'Car']

0      Chevrolet Chevelle Malibu
1              Buick Skylark 320
2             Plymouth Satellite
3                  AMC Rebel SST
4                    Ford Torino
                 ...
401              Ford Mustang GL
402            Volkswagen Pickup
403                Dodge Rampage
404                  Ford Ranger
405                   Chevy S-10
Name: Car, Length: 406, dtype: str

# 1.1 SET COLUMN VALUES

In [ ]:
# SET COLUMN VALUES
df.loc[:,'Car']='column changed'

# 1.2 CHECK [CAR] COLUMN CHANGES

In [8]:
df

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin
0,column changed,18.0,8.0,307.0,130.0,3504,12.0,70,US
1,column changed,15.0,8.0,350.0,165.0,3693,11.5,70,US
2,column changed,18.0,8.0,318.0,150.0,3436,NaN,70,US
3,column changed,16.0,8.0,304.0,150.0,3433,12.0,70,US
4,column changed,17.0,8.0,302.0,140.0,3449,10.5,70,US
...,...,...,...,...,...,...,...,...,...
401,column changed,27.0,4.0,140.0,86.0,2790,15.6,82,US
402,column changed,44.0,4.0,97.0,52.0,2130,24.6,82,Europe
403,column changed,32.0,4.0,135.0,84.0,2295,11.6,82,US
404,column changed,28.0,4.0,120.0,79.0,2625,18.6,82,US
405,column changed,31.0,4.0,119.0,82.0,2720,19.4,82,US

# 2. GET COLUMN VALUES IN RANGE

In [13]:
# GET COLUMN RANGE
df.loc[:,'Car':'Cylinders']

                           Car   MPG  Cylinders
0    Chevrolet Chevelle Malibu  18.0        8.0
1            Buick Skylark 320  15.0        8.0
2           Plymouth Satellite  18.0        8.0
3                AMC Rebel SST  16.0        8.0
4                  Ford Torino  17.0        8.0
..                         ...   ...        ...
401            Ford Mustang GL  27.0        4.0
402          Volkswagen Pickup  44.0        4.0
403              Dodge Rampage  32.0        4.0
404                Ford Ranger  28.0        4.0
405                 Chevy S-10  31.0        4.0

[406 rows x 3 columns]

# 2.2 SET COLUMN VALUES IN RANGE

In [14]:
# SET COLUMN RANGE VALUES
df.loc[:,'Car':'Cylinders']=['range_column_changed',0.0,0.0]

# 2.3 CHECK [CAR,MPG,CYCLINDERS] COLUMN CHANGES

In [15]:
df

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin
0,range_column_changed,0.0,0.0,307.0,130.0,3504,12.0,70,US
1,range_column_changed,0.0,0.0,350.0,165.0,3693,11.5,70,US
2,range_column_changed,0.0,0.0,318.0,150.0,3436,NaN,70,US
3,range_column_changed,0.0,0.0,304.0,150.0,3433,12.0,70,US
4,range_column_changed,0.0,0.0,302.0,140.0,3449,10.5,70,US
...,...,...,...,...,...,...,...,...,...
401,range_column_changed,0.0,0.0,140.0,86.0,2790,15.6,82,US
402,range_column_changed,0.0,0.0,97.0,52.0,2130,24.6,82,Europe
403,range_column_changed,0.0,0.0,135.0,84.0,2295,11.6,82,US
404,range_column_changed,0.0,0.0,120.0,79.0,2625,18.6,82,US
405,range_column_changed,0.0,0.0,119.0,82.0,2720,19.4,82,US

# 3. GET INTERMITTENT COLUMN VALUES

In [17]:
# GET INTERMITENT COLUMN
df.loc[:,['Model','Origin']]

     Model  Origin
0       70      US
1       70      US
2       70      US
3       70      US
4       70      US
..     ...     ...
401     82      US
402     82  Europe
403     82      US
404     82      US
405     82      US

[406 rows x 2 columns]

# 3.1 SET INTERMITENT COLUMN VALUES

In [ ]:
# SET INTERMITENT COLUMN VALUES
df.loc[:,['Model','Origin']]=[100,'intermitent']

# 3.2 CHECK INTERMITTENT COLUMN CHANGES

In [ ]:
df

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin
0,Chevrolet Chevelle Malibu,18.0,8.0,307.0,130.0,3504,12.0,100,intermitent
1,Buick Skylark 320,15.0,8.0,350.0,165.0,3693,11.5,100,intermitent
2,Plymouth Satellite,18.0,8.0,318.0,150.0,3436,NaN,100,intermitent
3,AMC Rebel SST,16.0,8.0,304.0,150.0,3433,12.0,100,intermitent
4,Ford Torino,17.0,8.0,302.0,140.0,3449,10.5,100,intermitent
...,...,...,...,...,...,...,...,...,...
401,Ford Mustang GL,27.0,4.0,140.0,86.0,2790,15.6,100,intermitent
402,Volkswagen Pickup,44.0,4.0,97.0,52.0,2130,24.6,100,intermitent
403,Dodge Rampage,32.0,4.0,135.0,84.0,2295,11.6,100,intermitent
404,Ford Ranger,28.0,4.0,120.0,79.0,2625,18.6,100,intermitent
405,Chevy S-10,31.0,4.0,119.0,82.0,2720,19.4,100,intermitent