In [1]:
import pandas as pd

In [2]:
a=pd.read_csv('data/cars.csv')

In [3]:
a

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin
0,Chevrolet Chevelle Malibu,18.0,8.0,307.0,130.0,3504,12.0,70,US
1,Buick Skylark 320,15.0,8.0,350.0,165.0,3693,11.5,70,US
2,Plymouth Satellite,18.0,8.0,318.0,150.0,3436,NaN,70,US
3,AMC Rebel SST,16.0,8.0,304.0,150.0,3433,12.0,70,US
4,Ford Torino,17.0,8.0,302.0,140.0,3449,10.5,70,US
...,...,...,...,...,...,...,...,...,...
401,Ford Mustang GL,27.0,4.0,140.0,86.0,2790,15.6,82,US
402,Volkswagen Pickup,44.0,4.0,97.0,52.0,2130,24.6,82,Europe
403,Dodge Rampage,32.0,4.0,135.0,84.0,2295,11.6,82,US
404,Ford Ranger,28.0,4.0,120.0,79.0,2625,18.6,82,US
405,Chevy S-10,31.0,4.0,119.0,82.0,2720,19.4,82,US

In [ ]:
# ONE ROW AND ONE COLUMN
a.loc[0,'Car']

'Chevrolet Chevelle Malibu'

In [11]:
#ONE COMPLETE VALUES
a.loc[0]

Car             Chevrolet Chevelle Malibu
MPG                                  18.0
Cylinders                             8.0
Displacement                        307.0
Horsepower                          130.0
Weight                               3504
Acceleration                         12.0
Model                                  70
Origin                                 US
Name: 0, dtype: object

In [12]:
# ONE SPECIFIC COLUMN
a.loc[:,'Origin']

0          US
1          US
2          US
3          US
4          US
        ...
401        US
402    Europe
403        US
404        US
405        US
Name: Origin, Length: 406, dtype: str

In [ ]:
# INTERMITENT ROWS AND CONTINIOUS COLUMNS
a.loc[[1,3,5,7],:]

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin
1,Buick Skylark 320,15.0,8.0,350.0,165.0,3693,11.5,70,US
3,AMC Rebel SST,16.0,8.0,304.0,150.0,3433,12.0,70,US
5,Ford Galaxie 500,15.0,8.0,429.0,198.0,4341,10.0,70,US
7,Plymouth Fury iii,14.0,NaN,440.0,215.0,4312,8.5,70,US

In [5]:

# INTERMITENT ROWS AND INTERMITENT COLUMNS
a.loc[[1,3,5,7],['Car','Model']]

                 Car  Model
1  Buick Skylark 320     70
3      AMC Rebel SST     70
5   Ford Galaxie 500     70
7  Plymouth Fury iii     70

# prefix and suffix

In [11]:
# ADD PREFIX IN COLUMN
a.add_prefix('PREFIX_',axis=1)

,PREFIX_Car,PREFIX_MPG,PREFIX_Cylinders,PREFIX_Displacement,PREFIX_Horsepower,PREFIX_Weight,PREFIX_Acceleration,PREFIX_Model,PREFIX_Origin
0,Chevrolet Chevelle Malibu,18.0,8.0,307.0,130.0,3504,12.0,70,US
1,Buick Skylark 320,15.0,8.0,350.0,165.0,3693,11.5,70,US
2,Plymouth Satellite,18.0,8.0,318.0,150.0,3436,NaN,70,US
3,AMC Rebel SST,16.0,8.0,304.0,150.0,3433,12.0,70,US
4,Ford Torino,17.0,8.0,302.0,140.0,3449,10.5,70,US
...,...,...,...,...,...,...,...,...,...
401,Ford Mustang GL,27.0,4.0,140.0,86.0,2790,15.6,82,US
402,Volkswagen Pickup,44.0,4.0,97.0,52.0,2130,24.6,82,Europe
403,Dodge Rampage,32.0,4.0,135.0,84.0,2295,11.6,82,US
404,Ford Ranger,28.0,4.0,120.0,79.0,2625,18.6,82,US
405,Chevy S-10,31.0,4.0,119.0,82.0,2720,19.4,82,US

In [12]:
# ADD PREFIX IN ROW
a.add_prefix('PREFIX_',axis=0)

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin
PREFIX_0,Chevrolet Chevelle Malibu,18.0,8.0,307.0,130.0,3504,12.0,70,US
PREFIX_1,Buick Skylark 320,15.0,8.0,350.0,165.0,3693,11.5,70,US
PREFIX_2,Plymouth Satellite,18.0,8.0,318.0,150.0,3436,NaN,70,US
PREFIX_3,AMC Rebel SST,16.0,8.0,304.0,150.0,3433,12.0,70,US
PREFIX_4,Ford Torino,17.0,8.0,302.0,140.0,3449,10.5,70,US
...,...,...,...,...,...,...,...,...,...
PREFIX_401,Ford Mustang GL,27.0,4.0,140.0,86.0,2790,15.6,82,US
PREFIX_402,Volkswagen Pickup,44.0,4.0,97.0,52.0,2130,24.6,82,Europe
PREFIX_403,Dodge Rampage,32.0,4.0,135.0,84.0,2295,11.6,82,US
PREFIX_404,Ford Ranger,28.0,4.0,120.0,79.0,2625,18.6,82,US
PREFIX_405,Chevy S-10,31.0,4.0,119.0,82.0,2720,19.4,82,US

In [14]:
# ADD SUFFIX IN ROW 
a.add_suffix('_SUFFIX',axis=0)

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin
0_SUFFIX,Chevrolet Chevelle Malibu,18.0,8.0,307.0,130.0,3504,12.0,70,US
1_SUFFIX,Buick Skylark 320,15.0,8.0,350.0,165.0,3693,11.5,70,US
2_SUFFIX,Plymouth Satellite,18.0,8.0,318.0,150.0,3436,NaN,70,US
3_SUFFIX,AMC Rebel SST,16.0,8.0,304.0,150.0,3433,12.0,70,US
4_SUFFIX,Ford Torino,17.0,8.0,302.0,140.0,3449,10.5,70,US
...,...,...,...,...,...,...,...,...,...
401_SUFFIX,Ford Mustang GL,27.0,4.0,140.0,86.0,2790,15.6,82,US
402_SUFFIX,Volkswagen Pickup,44.0,4.0,97.0,52.0,2130,24.6,82,Europe
403_SUFFIX,Dodge Rampage,32.0,4.0,135.0,84.0,2295,11.6,82,US
404_SUFFIX,Ford Ranger,28.0,4.0,120.0,79.0,2625,18.6,82,US
405_SUFFIX,Chevy S-10,31.0,4.0,119.0,82.0,2720,19.4,82,US

In [15]:
# ADD SUFFIX IN AOLUMN
a.add_suffix('_SUFFIX',axis=1)

,Car_SUFFIX,MPG_SUFFIX,Cylinders_SUFFIX,Displacement_SUFFIX,Horsepower_SUFFIX,Weight_SUFFIX,Acceleration_SUFFIX,Model_SUFFIX,Origin_SUFFIX
0,Chevrolet Chevelle Malibu,18.0,8.0,307.0,130.0,3504,12.0,70,US
1,Buick Skylark 320,15.0,8.0,350.0,165.0,3693,11.5,70,US
2,Plymouth Satellite,18.0,8.0,318.0,150.0,3436,NaN,70,US
3,AMC Rebel SST,16.0,8.0,304.0,150.0,3433,12.0,70,US
4,Ford Torino,17.0,8.0,302.0,140.0,3449,10.5,70,US
...,...,...,...,...,...,...,...,...,...
401,Ford Mustang GL,27.0,4.0,140.0,86.0,2790,15.6,82,US
402,Volkswagen Pickup,44.0,4.0,97.0,52.0,2130,24.6,82,Europe
403,Dodge Rampage,32.0,4.0,135.0,84.0,2295,11.6,82,US
404,Ford Ranger,28.0,4.0,120.0,79.0,2625,18.6,82,US
405,Chevy S-10,31.0,4.0,119.0,82.0,2720,19.4,82,US

# min and max

In [10]:
# SPECIFIC COLUMN MINIMUM VALUES
a['MPG'].idxmin()

10

In [ ]:
# SPECIFIC COLUMN MAXIMUM VALUES
a['MPG'].idxmax()

329

In [ ]:
# SPECIFIC COLUMN MINIMUM **NUMPY VALUES
a['MPG'].argmin()

np.int64(10)

In [ ]:
# SPECIFIC COLUMN MAXIMUM **NUMPY VALUES
a['MPG'].argmax()

np.int64(329)