In [62]:
import pandas as pd

In [97]:
a=pd.read_csv('data/cars.csv')
a

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin
0,Chevrolet Chevelle Malibu,18.0,8.0,307.0,130.0,3504,12.0,70,US
1,Buick Skylark 320,15.0,8.0,350.0,165.0,3693,11.5,70,US
2,Plymouth Satellite,18.0,8.0,318.0,150.0,3436,NaN,70,US
3,AMC Rebel SST,16.0,8.0,304.0,150.0,3433,12.0,70,US
4,Ford Torino,17.0,8.0,302.0,140.0,3449,10.5,70,US
...,...,...,...,...,...,...,...,...,...
401,Ford Mustang GL,27.0,4.0,140.0,86.0,2790,15.6,82,US
402,Volkswagen Pickup,44.0,4.0,97.0,52.0,2130,24.6,82,Europe
403,Dodge Rampage,32.0,4.0,135.0,84.0,2295,11.6,82,US
404,Ford Ranger,28.0,4.0,120.0,79.0,2625,18.6,82,US
405,Chevy S-10,31.0,4.0,119.0,82.0,2720,19.4,82,US

# ONE ROW AND COLUMN DELETE METHOD
# INTERMITENT ROW AND COLUMN DELETE METHOD

In [64]:
# ONE ROW DELETE METHOD
a.drop(0,axis=0)

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin
1,Buick Skylark 320,15.0,8.0,350.0,165.0,3693,11.5,70,US
2,Plymouth Satellite,18.0,8.0,318.0,150.0,3436,NaN,70,US
3,AMC Rebel SST,16.0,8.0,304.0,150.0,3433,12.0,70,US
4,Ford Torino,17.0,8.0,302.0,140.0,3449,10.5,70,US
5,Ford Galaxie 500,15.0,8.0,429.0,198.0,4341,10.0,70,US
...,...,...,...,...,...,...,...,...,...
401,Ford Mustang GL,27.0,4.0,140.0,86.0,2790,15.6,82,US
402,Volkswagen Pickup,44.0,4.0,97.0,52.0,2130,24.6,82,Europe
403,Dodge Rampage,32.0,4.0,135.0,84.0,2295,11.6,82,US
404,Ford Ranger,28.0,4.0,120.0,79.0,2625,18.6,82,US
405,Chevy S-10,31.0,4.0,119.0,82.0,2720,19.4,82,US

In [65]:
# INTERMITENT ROW DELETE METHOD
a.drop([0,1,2,3],axis=0)

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin
4,Ford Torino,17.0,8.0,302.0,140.0,3449,10.5,70,US
5,Ford Galaxie 500,15.0,8.0,429.0,198.0,4341,10.0,70,US
6,Chevrolet Impala,14.0,8.0,454.0,220.0,4354,9.0,70,US
7,Plymouth Fury iii,14.0,NaN,440.0,215.0,4312,8.5,70,US
8,Pontiac Catalina,14.0,8.0,455.0,225.0,4425,10.0,70,US
...,...,...,...,...,...,...,...,...,...
401,Ford Mustang GL,27.0,4.0,140.0,86.0,2790,15.6,82,US
402,Volkswagen Pickup,44.0,4.0,97.0,52.0,2130,24.6,82,Europe
403,Dodge Rampage,32.0,4.0,135.0,84.0,2295,11.6,82,US
404,Ford Ranger,28.0,4.0,120.0,79.0,2625,18.6,82,US
405,Chevy S-10,31.0,4.0,119.0,82.0,2720,19.4,82,US

In [66]:
# ONE COLUMN DELETE METHOD
a.drop('Car',axis=1)

,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin
0,18.0,8.0,307.0,130.0,3504,12.0,70,US
1,15.0,8.0,350.0,165.0,3693,11.5,70,US
2,18.0,8.0,318.0,150.0,3436,NaN,70,US
3,16.0,8.0,304.0,150.0,3433,12.0,70,US
4,17.0,8.0,302.0,140.0,3449,10.5,70,US
...,...,...,...,...,...,...,...,...
401,27.0,4.0,140.0,86.0,2790,15.6,82,US
402,44.0,4.0,97.0,52.0,2130,24.6,82,Europe
403,32.0,4.0,135.0,84.0,2295,11.6,82,US
404,28.0,4.0,120.0,79.0,2625,18.6,82,US
405,31.0,4.0,119.0,82.0,2720,19.4,82,US

In [67]:
# INTERMITENT COLUMN DELETE METHOD
a.drop(columns=['Car','MPG'],axis=0)

     Cylinders  Displacement  Horsepower  Weight  Acceleration  Model  Origin
0          8.0         307.0       130.0    3504          12.0     70      US
1          8.0         350.0       165.0    3693          11.5     70      US
2          8.0         318.0       150.0    3436           NaN     70      US
3          8.0         304.0       150.0    3433          12.0     70      US
4          8.0         302.0       140.0    3449          10.5     70      US
..         ...           ...         ...     ...           ...    ...     ...
401        4.0         140.0        86.0    2790          15.6     82      US
402        4.0          97.0        52.0    2130          24.6     82  Europe
403        4.0         135.0        84.0    2295          11.6     82      US
404        4.0         120.0        79.0    2625          18.6     82      US
405        4.0         119.0        82.0    2720          19.4     82      US

[406 rows x 7 columns]

 # POP DELETE METHOD

In [68]:
# POP DELETE
a.pop('MPG')

0      18.0
1      15.0
2      18.0
3      16.0
4      17.0
       ...
401    27.0
402    44.0
403    32.0
404    28.0
405    31.0
Name: MPG, Length: 406, dtype: float64

In [69]:
# POP AFTER OUPUT
a

,Car,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin
0,Chevrolet Chevelle Malibu,8.0,307.0,130.0,3504,12.0,70,US
1,Buick Skylark 320,8.0,350.0,165.0,3693,11.5,70,US
2,Plymouth Satellite,8.0,318.0,150.0,3436,NaN,70,US
3,AMC Rebel SST,8.0,304.0,150.0,3433,12.0,70,US
4,Ford Torino,8.0,302.0,140.0,3449,10.5,70,US
...,...,...,...,...,...,...,...,...
401,Ford Mustang GL,4.0,140.0,86.0,2790,15.6,82,US
402,Volkswagen Pickup,4.0,97.0,52.0,2130,24.6,82,Europe
403,Dodge Rampage,4.0,135.0,84.0,2295,11.6,82,US
404,Ford Ranger,4.0,120.0,79.0,2625,18.6,82,US
405,Chevy S-10,4.0,119.0,82.0,2720,19.4,82,US

# TRUNCATE METHOD

In [98]:
# TRUNCATE RANGE WISE SELECT DELETE METHOD
# RULE 1 : INDEX NO SUFFLE
a.truncate(1,10,axis=0)

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin
1,Buick Skylark 320,15.0,8.0,350.0,165.0,3693,11.5,70,US
2,Plymouth Satellite,18.0,8.0,318.0,150.0,3436,NaN,70,US
3,AMC Rebel SST,16.0,8.0,304.0,150.0,3433,12.0,70,US
4,Ford Torino,17.0,8.0,302.0,140.0,3449,10.5,70,US
5,Ford Galaxie 500,15.0,8.0,429.0,198.0,4341,10.0,70,US
6,Chevrolet Impala,14.0,8.0,454.0,220.0,4354,9.0,70,US
7,Plymouth Fury iii,14.0,NaN,440.0,215.0,4312,8.5,70,US
8,Pontiac Catalina,14.0,8.0,455.0,225.0,4425,10.0,70,US
9,AMC Ambassador DPL,15.0,8.0,390.0,190.0,3850,8.5,70,US
10,Citroen DS-21 Pallas,0.0,4.0,133.0,115.0,3090,17.5,70,Europe

In [99]:
# 1. Sort the columns alphabetically
a = a.sort_index(axis=1)

# 2. Run the truncate function
a = a.truncate(before='Car', after='Cylinders', axis=1)

In [100]:
a

                           Car  Cylinders
0    Chevrolet Chevelle Malibu        8.0
1            Buick Skylark 320        8.0
2           Plymouth Satellite        8.0
3                AMC Rebel SST        8.0
4                  Ford Torino        8.0
..                         ...        ...
401            Ford Mustang GL        4.0
402          Volkswagen Pickup        4.0
403              Dodge Rampage        4.0
404                Ford Ranger        4.0
405                 Chevy S-10        4.0

[406 rows x 2 columns]