# FILTERING DATA LOC [ ]

In [1]:
import pandas as pd

In [2]:
a=pd.read_csv('data/cars.csv')
a

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin
0,Chevrolet Chevelle Malibu,18.0,8.0,307.0,130.0,3504,12.0,70,US
1,Buick Skylark 320,15.0,8.0,350.0,165.0,3693,11.5,70,US
2,Plymouth Satellite,18.0,8.0,318.0,150.0,3436,NaN,70,US
3,AMC Rebel SST,16.0,8.0,304.0,150.0,3433,12.0,70,US
4,Ford Torino,17.0,8.0,302.0,140.0,3449,10.5,70,US
...,...,...,...,...,...,...,...,...,...
401,Ford Mustang GL,27.0,4.0,140.0,86.0,2790,15.6,82,US
402,Volkswagen Pickup,44.0,4.0,97.0,52.0,2130,24.6,82,Europe
403,Dodge Rampage,32.0,4.0,135.0,84.0,2295,11.6,82,US
404,Ford Ranger,28.0,4.0,120.0,79.0,2625,18.6,82,US
405,Chevy S-10,31.0,4.0,119.0,82.0,2720,19.4,82,US

In [ ]:
# CONDITION 
a['MPG']>=30

0      False
1      False
2      False
3      False
4      False
       ...
401    False
402     True
403     True
404    False
405     True
Name: MPG, Length: 406, dtype: bool

In [ ]:
# APPLY LOC FOR FILTERED DATA
a.loc[a['MPG']>=30]

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin
58,Peugeot 304,30.0,4.0,79.0,70.0,2074,19.5,71,Europe
59,Fiat 124B,30.0,4.0,88.0,76.0,2065,14.5,71,Europe
60,Toyota Corolla 1200,31.0,4.0,71.0,65.0,1773,19.0,71,Japan
61,Datsun 1200,35.0,4.0,72.0,69.0,1613,18.0,71,Japan
136,Datsun B210,31.0,4.0,79.0,67.0,1950,19.0,74,Japan
...,...,...,...,...,...,...,...,...,...
398,Toyota Celica GT,32.0,4.0,144.0,96.0,2665,13.9,82,Japan
399,Dodge Charger 2.2,36.0,4.0,135.0,84.0,2370,13.0,82,US
402,Volkswagen Pickup,44.0,4.0,97.0,52.0,2130,24.6,82,Europe
403,Dodge Rampage,32.0,4.0,135.0,84.0,2295,11.6,82,US
405,Chevy S-10,31.0,4.0,119.0,82.0,2720,19.4,82,US

In [10]:
a.loc[ a['Origin']=='US',['Car','MPG']]

                           Car   MPG
0    Chevrolet Chevelle Malibu  18.0
1            Buick Skylark 320  15.0
2           Plymouth Satellite  18.0
3                AMC Rebel SST  16.0
4                  Ford Torino  17.0
..                         ...   ...
400           Chevrolet Camaro  27.0
401            Ford Mustang GL  27.0
403              Dodge Rampage  32.0
404                Ford Ranger  28.0
405                 Chevy S-10  31.0

[254 rows x 2 columns]

# FILTER METHOD

In [ ]:
# FILTER METHOD USING ROW
a.filter(items=[1,2,3],axis=0)

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin
1,Buick Skylark 320,15.0,8.0,350.0,165.0,3693,11.5,70,US
2,Plymouth Satellite,18.0,8.0,318.0,150.0,3436,NaN,70,US
3,AMC Rebel SST,16.0,8.0,304.0,150.0,3433,12.0,70,US

In [ ]:
# FILTER METHOD USING COLUMN
a.filter(items=['Car','MPG'],axis=1)

                           Car   MPG
0    Chevrolet Chevelle Malibu  18.0
1            Buick Skylark 320  15.0
2           Plymouth Satellite  18.0
3                AMC Rebel SST  16.0
4                  Ford Torino  17.0
..                         ...   ...
401            Ford Mustang GL  27.0
402          Volkswagen Pickup  44.0
403              Dodge Rampage  32.0
404                Ford Ranger  28.0
405                 Chevy S-10  31.0

[406 rows x 2 columns]