In [1]:
import pandas as pd

In [62]:
df=pd.read_csv('Dataset/cars.csv')
df

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin
0,Chevrolet Chevelle Malibu,18.0,8.0,307.0,130.0,3504,12.0,70,US
1,Buick Skylark 320,15.0,8.0,350.0,165.0,3693,11.5,70,US
2,Plymouth Satellite,18.0,8.0,318.0,150.0,3436,NaN,70,US
3,AMC Rebel SST,16.0,8.0,304.0,150.0,3433,12.0,70,US
4,Ford Torino,17.0,8.0,302.0,140.0,3449,10.5,70,US
...,...,...,...,...,...,...,...,...,...
401,Ford Mustang GL,27.0,4.0,140.0,86.0,2790,15.6,82,US
402,Volkswagen Pickup,44.0,4.0,97.0,52.0,2130,24.6,82,Europe
403,Dodge Rampage,32.0,4.0,135.0,84.0,2295,11.6,82,US
404,Ford Ranger,28.0,4.0,120.0,79.0,2625,18.6,82,US
405,Chevy S-10,31.0,4.0,119.0,82.0,2720,19.4,82,US

# 1. DELETE ROWS INDEX METHOD

In [ ]:
# ONE ROW DELETE METHOD (AXIS=0)
df.drop(0,axis=0)

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin
1,Buick Skylark 320,15.0,8.0,350.0,165.0,3693,11.5,70,US
2,Plymouth Satellite,18.0,8.0,318.0,150.0,3436,NaN,70,US
3,AMC Rebel SST,16.0,8.0,304.0,150.0,3433,12.0,70,US
4,Ford Torino,17.0,8.0,302.0,140.0,3449,10.5,70,US
5,Ford Galaxie 500,15.0,8.0,429.0,198.0,4341,10.0,70,US
...,...,...,...,...,...,...,...,...,...
401,Ford Mustang GL,27.0,4.0,140.0,86.0,2790,15.6,82,US
402,Volkswagen Pickup,44.0,4.0,97.0,52.0,2130,24.6,82,Europe
403,Dodge Rampage,32.0,4.0,135.0,84.0,2295,11.6,82,US
404,Ford Ranger,28.0,4.0,120.0,79.0,2625,18.6,82,US
405,Chevy S-10,31.0,4.0,119.0,82.0,2720,19.4,82,US

# 1.1 DELETE ROWS INTERMITTENT METHOD

In [18]:
# INTERMITENT ROW DELETE METHOD
df.drop([0,1,2,3,4],axis=0)

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin
5,Ford Galaxie 500,15.0,8.0,429.0,198.0,4341,10.0,70,US
6,Chevrolet Impala,14.0,8.0,454.0,220.0,4354,9.0,70,US
7,Plymouth Fury iii,14.0,NaN,440.0,215.0,4312,8.5,70,US
8,Pontiac Catalina,14.0,8.0,455.0,225.0,4425,10.0,70,US
9,AMC Ambassador DPL,15.0,8.0,390.0,190.0,3850,8.5,70,US
...,...,...,...,...,...,...,...,...,...
401,Ford Mustang GL,27.0,4.0,140.0,86.0,2790,15.6,82,US
402,Volkswagen Pickup,44.0,4.0,97.0,52.0,2130,24.6,82,Europe
403,Dodge Rampage,32.0,4.0,135.0,84.0,2295,11.6,82,US
404,Ford Ranger,28.0,4.0,120.0,79.0,2625,18.6,82,US
405,Chevy S-10,31.0,4.0,119.0,82.0,2720,19.4,82,US

# 2. DELETE COLUMN

In [20]:
# ONE COLUMN DELETE METHOD (AXIS=1),COLUMN=['CAR']
#df.drop(column=['Car'],axis=1)
df.drop(['Car'],axis=1)

,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin
0,18.0,8.0,307.0,130.0,3504,12.0,70,US
1,15.0,8.0,350.0,165.0,3693,11.5,70,US
2,18.0,8.0,318.0,150.0,3436,NaN,70,US
3,16.0,8.0,304.0,150.0,3433,12.0,70,US
4,17.0,8.0,302.0,140.0,3449,10.5,70,US
...,...,...,...,...,...,...,...,...
401,27.0,4.0,140.0,86.0,2790,15.6,82,US
402,44.0,4.0,97.0,52.0,2130,24.6,82,Europe
403,32.0,4.0,135.0,84.0,2295,11.6,82,US
404,28.0,4.0,120.0,79.0,2625,18.6,82,US
405,31.0,4.0,119.0,82.0,2720,19.4,82,US

# 2.1 DELETE COLUMN INTERMITTENT METHOD

In [25]:
# INTERMITENT COLUMN DELETE METHOD
df.drop(['MPG','Model','Origin'],axis=1)

,Car,Cylinders,Displacement,Horsepower,Weight,Acceleration
0,Chevrolet Chevelle Malibu,8.0,307.0,130.0,3504,12.0
1,Buick Skylark 320,8.0,350.0,165.0,3693,11.5
2,Plymouth Satellite,8.0,318.0,150.0,3436,NaN
3,AMC Rebel SST,8.0,304.0,150.0,3433,12.0
4,Ford Torino,8.0,302.0,140.0,3449,10.5
...,...,...,...,...,...,...
401,Ford Mustang GL,4.0,140.0,86.0,2790,15.6
402,Volkswagen Pickup,4.0,97.0,52.0,2130,24.6
403,Dodge Rampage,4.0,135.0,84.0,2295,11.6
404,Ford Ranger,4.0,120.0,79.0,2625,18.6
405,Chevy S-10,4.0,119.0,82.0,2720,19.4

 # 3. POP DELETE METHOD

In [42]:
# (ctrl + X) ---> cut and stored one variable
cut_pop= df.pop('MPG')

# 3.1 CHECK POP

In [43]:
cut_pop

0      18.0
1      15.0
2      18.0
3      16.0
4      17.0
       ...
401    27.0
402    44.0
403    32.0
404    28.0
405    31.0
Name: MPG, Length: 406, dtype: float64

# 4. DELETE ROW TRUNCATE METHOD

In [60]:
# TRUNCATE RANGE WISE SELECT DELETE METHOD
# (ctrl + X) ---> cut and stored one variable
# RULE 1 : INDEX NO SUFFLE
cut_trunc_row= df.truncate(0,10,axis=0)

# 4.1 CHECK TRUNCATE ROW

In [61]:
cut_trunc_row

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin
0,Chevrolet Chevelle Malibu,18.0,8.0,307.0,130.0,3504,12.0,70,US
1,Buick Skylark 320,15.0,8.0,350.0,165.0,3693,11.5,70,US
2,Plymouth Satellite,18.0,8.0,318.0,150.0,3436,NaN,70,US
3,AMC Rebel SST,16.0,8.0,304.0,150.0,3433,12.0,70,US
4,Ford Torino,17.0,8.0,302.0,140.0,3449,10.5,70,US
5,Ford Galaxie 500,15.0,8.0,429.0,198.0,4341,10.0,70,US
6,Chevrolet Impala,14.0,8.0,454.0,220.0,4354,9.0,70,US
7,Plymouth Fury iii,14.0,NaN,440.0,215.0,4312,8.5,70,US
8,Pontiac Catalina,14.0,8.0,455.0,225.0,4425,10.0,70,US
9,AMC Ambassador DPL,15.0,8.0,390.0,190.0,3850,8.5,70,US
10,Citroen DS-21 Pallas,0.0,4.0,133.0,115.0,3090,17.5,70,Europe

# 5. DELETE COLUMN TRUNCATE METHOD

In [ ]:
# 1. Must Sort the columns alphabetically
sort = df.sort_index(axis=1)
sort

,Acceleration,Car,Cylinders,Displacement,Horsepower,MPG,Model,Origin,Weight
0,12.0,Chevrolet Chevelle Malibu,8.0,307.0,130.0,18.0,70,US,3504
1,11.5,Buick Skylark 320,8.0,350.0,165.0,15.0,70,US,3693
2,NaN,Plymouth Satellite,8.0,318.0,150.0,18.0,70,US,3436
3,12.0,AMC Rebel SST,8.0,304.0,150.0,16.0,70,US,3433
4,10.5,Ford Torino,8.0,302.0,140.0,17.0,70,US,3449
...,...,...,...,...,...,...,...,...,...
401,15.6,Ford Mustang GL,4.0,140.0,86.0,27.0,82,US,2790
402,24.6,Volkswagen Pickup,4.0,97.0,52.0,44.0,82,Europe,2130
403,11.6,Dodge Rampage,4.0,135.0,84.0,32.0,82,US,2295
404,18.6,Ford Ranger,4.0,120.0,79.0,28.0,82,US,2625
405,19.4,Chevy S-10,4.0,119.0,82.0,31.0,82,US,2720

In [ ]:
# 2. Then Run the truncate function
# (ctrl + X) ---> cut and stored one variable
cut_trunc_col= sort.truncate(before='Model',after='Origin',axis=1)

# 5.1 CHECK TRUNCATE COLUMN

In [72]:
cut_trunc_col

     Model  Origin
0       70      US
1       70      US
2       70      US
3       70      US
4       70      US
..     ...     ...
401     82      US
402     82  Europe
403     82      US
404     82      US
405     82      US

[406 rows x 2 columns]