In [1]:
import pandas as pd

In [4]:
values={
    'A':[5,10,15,20],
    'B':[2,4,6,8],
    'C':[1,3,5,7]
}

df=pd.DataFrame(values)
df

    A  B  C
0   5  2  1
1  10  4  3
2  15  6  5
3  20  8  7

In [27]:
# Addition
df.add(10)

    A   B   C
0  15  12  11
1  20  14  13
2  25  16  15
3  30  18  17

In [28]:
# Subtraction
df.sub(1)

    A  B  C
0   4  1  0
1   9  3  2
2  14  5  4
3  19  7  6

In [ ]:
# Subtraction
df.subtract(1)

    A  B  C
0   4  1  0
1   9  3  2
2  14  5  4
3  19  7  6

In [ ]:
# Multiplication
df.mul(2)

    A   B   C
0  10   4   2
1  20   8   6
2  30  12  10
3  40  16  14

In [ ]:
# Multiplication
df.mul(2)

    A   B   C
0  10   4   2
1  20   8   6
2  30  12  10
3  40  16  14

In [ ]:
# Division
df.div(2)

      A    B    C
0   2.5  1.0  0.5
1   5.0  2.0  1.5
2   7.5  3.0  2.5
3  10.0  4.0  3.5

In [ ]:
# Division
df.divide(2)

      A    B    C
0   2.5  1.0  0.5
1   5.0  2.0  1.5
2   7.5  3.0  2.5
3  10.0  4.0  3.5

In [ ]:
# Floor Division
df.floordiv(2)

    A  B  C
0   2  1  0
1   5  2  1
2   7  3  2
3  10  4  3

In [25]:
df

    A  B  C
0   5  2  1
1  10  4  3
2  15  6  5
3  20  8  7

In [30]:
# Modulus
df.mod(2)

   A  B  C
0  1  0  1
1  0  0  1
2  1  0  1
3  0  0  1

In [ ]:
# Power
df.pow(2)

     A   B   C
0   25   4   1
1  100  16   9
2  225  36  25
3  400  64  49

# .Dot method

In [40]:
a=pd.DataFrame(
    {
    'A':[1,2],
    'B':[4,5]
    }
)

In [41]:
a

   A  B
0  1  4
1  2  5

In [38]:
b=pd.DataFrame(
    {
    'A':[1,2,3],
    'B':[4,5,6]
    }
)

In [39]:
b

   A  B
0  1  4
1  2  5
2  3  6

In [42]:
a.dot(b)

ValueError: matrices are not aligned