# FUNCTIONS

In [3]:
import pandas as pd

In [23]:
a=pd.read_csv('data/cars.csv')
a

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin
0,Chevrolet Chevelle Malibu,18.0,8.0,307.0,130.0,3504,12.0,70,US
1,Buick Skylark 320,15.0,8.0,350.0,165.0,3693,11.5,70,US
2,Plymouth Satellite,18.0,8.0,318.0,150.0,3436,NaN,70,US
3,AMC Rebel SST,16.0,8.0,304.0,150.0,3433,12.0,70,US
4,Ford Torino,17.0,8.0,302.0,140.0,3449,10.5,70,US
...,...,...,...,...,...,...,...,...,...
401,Ford Mustang GL,27.0,4.0,140.0,86.0,2790,15.6,82,US
402,Volkswagen Pickup,44.0,4.0,97.0,52.0,2130,24.6,82,Europe
403,Dodge Rampage,32.0,4.0,135.0,84.0,2295,11.6,82,US
404,Ford Ranger,28.0,4.0,120.0,79.0,2625,18.6,82,US
405,Chevy S-10,31.0,4.0,119.0,82.0,2720,19.4,82,US

# 1.CUSTOM FUNCTION WITH SERIES ARGUMENTS

In [30]:
# SERIES ARGUMENTS
def convert_one(word:str): # STR--> ONE COLUMN
    return word.lower().replace(" ","");

In [31]:
# ARGUMENTS ALREADY (STRING DATA TYPES) BECUASE ONE COLUMN SO DIRECTLY APPLY
a['Car'].apply(convert_one)

0      chevroletchevellemalibu
1              buickskylark320
2            plymouthsatellite
3                  amcrebelsst
4                   fordtorino
                ...
401              fordmustanggl
402           volkswagenpickup
403               dodgerampage
404                 fordranger
405                  chevys-10
Name: Car, Length: 406, dtype: str

# 2.CUSTOM FUNCTION WITH DATA FRAMES SERIES ARGUMENTS

In [25]:
# DATA FRAME SERIES ARGUMENTS
def convert_double(COLUMN:pd.Series): # PD.SERIES--> MORE COLUMN
    return COLUMN.str.lower().str.replace(" ",""); # EACH FUNCTION LIKE LOWER,UPPER USE **(.STR) BECAUSE DATAFRAME SERIES ARGUMENTS MORE COLUMN

In [29]:
# SRORE COLUMNS IN VAIRABLE
dfq=a[['Car','Origin',]]
dfq

                           Car  Origin   MPG
0    Chevrolet Chevelle Malibu      US  18.0
1            Buick Skylark 320      US  15.0
2           Plymouth Satellite      US  18.0
3                AMC Rebel SST      US  16.0
4                  Ford Torino      US  17.0
..                         ...     ...   ...
401            Ford Mustang GL      US  27.0
402          Volkswagen Pickup  Europe  44.0
403              Dodge Rampage      US  32.0
404                Ford Ranger      US  28.0
405                 Chevy S-10      US  31.0

[406 rows x 3 columns]

In [27]:
# dfq --> TWO OR MORE COLUMN STORE ONE VARIABLE THEN USE THIS
dfq.apply(convert_double)

                         Car  Origin
0    chevroletchevellemalibu      us
1            buickskylark320      us
2          plymouthsatellite      us
3                amcrebelsst      us
4                 fordtorino      us
..                       ...     ...
401            fordmustanggl      us
402         volkswagenpickup  europe
403             dodgerampage      us
404               fordranger      us
405                chevys-10      us

[406 rows x 2 columns]

# 3.ASSIGN FUNCTION

In [ ]:
# FUNCTION
def columns_mdify_insert(col):
    return col*2

In [ ]:
# SYNTAX --> a.assign(new column | exixting column = function_name(column_name))
a.assign(Cylinders=columns_mdify_insert(a['Cylinders']))

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin
0,Chevrolet Chevelle Malibu,18.0,16.0,307.0,130.0,3504,12.0,70,US
1,Buick Skylark 320,15.0,16.0,350.0,165.0,3693,11.5,70,US
2,Plymouth Satellite,18.0,16.0,318.0,150.0,3436,NaN,70,US
3,AMC Rebel SST,16.0,16.0,304.0,150.0,3433,12.0,70,US
4,Ford Torino,17.0,16.0,302.0,140.0,3449,10.5,70,US
...,...,...,...,...,...,...,...,...,...
401,Ford Mustang GL,27.0,8.0,140.0,86.0,2790,15.6,82,US
402,Volkswagen Pickup,44.0,8.0,97.0,52.0,2130,24.6,82,Europe
403,Dodge Rampage,32.0,8.0,135.0,84.0,2295,11.6,82,US
404,Ford Ranger,28.0,8.0,120.0,79.0,2625,18.6,82,US
405,Chevy S-10,31.0,8.0,119.0,82.0,2720,19.4,82,US

# 4.AGGREGATE FUNCTIONS

In [ ]:
# SUM
a['Cylinders'].sum()

np.float64(2215.0)

In [ ]:
# PRODUCT
a['Cylinders'].product()

np.float64(4.2378626510690295e+290)

In [ ]:
# MEAN
a['Cylinders'].mean()

np.float64(5.469135802469136)

In [ ]:
# MEDIAN
a['Cylinders'].median()

np.float64(4.0)

In [ ]:
# MININUM
a['Cylinders'].min()

np.float64(3.0)

In [59]:
a['Cylinders'].max()

np.float64(8.0)

In [ ]:
# COUNT
a['Cylinders'].count()

np.int64(405)

In [ ]:
# STANDARD DEVIATION
a['Cylinders'].std()

np.float64(1.7096582061941765)

In [ ]:
# VARIANCE
a['Cylinders'].var()

np.float64(2.922931182007089)

In [ ]:
# TABLE FULL CACULATE THAT ARGUMENT USE
a.sum(numeric_only=True)

MPG                9358.8
Cylinders          2215.0
Displacement      79080.5
Horsepower        41771.0
Weight          1209642.0
Acceleration       6290.0
Model             30824.0
dtype: float64

# 5.GROUP BY FUNCTION

In [ ]:
# METHOD 1
a['Weight'].groupby(a['Origin']).max()

Origin
Europe    3820
Japan     2930
US        5140
Name: Weight, dtype: int64

In [ ]:
# METHOD 2
a.groupby('Origin')['Weight'].max()

Origin
Europe    3820
Japan     2930
US        5140
Name: Weight, dtype: int64

# 6.TRANSFORM FUNCTION

In [32]:
# YOU CAN STORE AGGREGATE RESULT IN NEW COLUMN USE **TRANSFORM 
a['transform']=a.groupby('Origin')['Weight'].transform('max')
a

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin,pipe,a1,transform
0,Chevrolet Chevelle Malibu,18.0,8.0,307.0,130.0,3504,12.0,70,US,7622.95,7622.9520,5140
1,Buick Skylark 320,15.0,8.0,350.0,165.0,3693,11.5,70,US,8034.12,8034.1215,5140
2,Plymouth Satellite,18.0,8.0,318.0,150.0,3436,NaN,70,US,7475.02,7475.0180,5140
3,AMC Rebel SST,16.0,8.0,304.0,150.0,3433,12.0,70,US,7468.49,7468.4915,5140
4,Ford Torino,17.0,8.0,302.0,140.0,3449,10.5,70,US,7503.30,7503.2995,5140
...,...,...,...,...,...,...,...,...,...,...,...,...
401,Ford Mustang GL,27.0,4.0,140.0,86.0,2790,15.6,82,US,6069.64,6069.6450,5140
402,Volkswagen Pickup,44.0,4.0,97.0,52.0,2130,24.6,82,Europe,4633.81,4633.8150,3820
403,Dodge Rampage,32.0,4.0,135.0,84.0,2295,11.6,82,US,4992.77,4992.7725,5140
404,Ford Ranger,28.0,4.0,120.0,79.0,2625,18.6,82,US,5710.69,5710.6875,5140
405,Chevy S-10,31.0,4.0,119.0,82.0,2720,19.4,82,US,5917.36,5917.3600,5140

# 7.MAP FUNCTION

In [ ]:
# COLUMN UNIQE VALUES ONLY DISPLAY
a['Origin'].unique()

<StringArray>
['US', 'Europe', 'Japan']
Length: 3, dtype: str

In [33]:
# EXISTING COLUMN NEW VALUE SET THEN NEW COLUMN ADD
a['map_set']=a['Origin'].map({
    'US':1,
    'Europe':2,
    'Japan':3
})
a

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin,pipe,a1,transform,map_set
0,Chevrolet Chevelle Malibu,18.0,8.0,307.0,130.0,3504,12.0,70,US,7622.95,7622.9520,5140,1
1,Buick Skylark 320,15.0,8.0,350.0,165.0,3693,11.5,70,US,8034.12,8034.1215,5140,1
2,Plymouth Satellite,18.0,8.0,318.0,150.0,3436,NaN,70,US,7475.02,7475.0180,5140,1
3,AMC Rebel SST,16.0,8.0,304.0,150.0,3433,12.0,70,US,7468.49,7468.4915,5140,1
4,Ford Torino,17.0,8.0,302.0,140.0,3449,10.5,70,US,7503.30,7503.2995,5140,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
401,Ford Mustang GL,27.0,4.0,140.0,86.0,2790,15.6,82,US,6069.64,6069.6450,5140,1
402,Volkswagen Pickup,44.0,4.0,97.0,52.0,2130,24.6,82,Europe,4633.81,4633.8150,3820,2
403,Dodge Rampage,32.0,4.0,135.0,84.0,2295,11.6,82,US,4992.77,4992.7725,5140,1
404,Ford Ranger,28.0,4.0,120.0,79.0,2625,18.6,82,US,5710.69,5710.6875,5140,1
405,Chevy S-10,31.0,4.0,119.0,82.0,2720,19.4,82,US,5917.36,5917.3600,5140,1

# 8.Lambda function

In [ ]:
# LAMBDA FUNCTION-->(lambda argument:expression)
a['Cylinders'].apply(lambda x:x-5)

0      3.0
1      3.0
2      3.0
3      3.0
4      3.0
      ...
401   -1.0
402   -1.0
403   -1.0
404   -1.0
405   -1.0
Name: Cylinders, Length: 406, dtype: float64

# 9.PIPE FUNCTION

In [29]:
# FUNCTION 1
def pipe1(col1):
    return col1*2.1755

# FUNCTION 2 
def pipe2(col2):
    return round(col2,2)

In [30]:
# METHOD 1
a['a1']=a['Weight'].apply(pipe1)
a

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin,pipe,a1
0,Chevrolet Chevelle Malibu,18.0,8.0,307.0,130.0,3504,12.0,70,US,7622.95,7622.9520
1,Buick Skylark 320,15.0,8.0,350.0,165.0,3693,11.5,70,US,8034.12,8034.1215
2,Plymouth Satellite,18.0,8.0,318.0,150.0,3436,NaN,70,US,7475.02,7475.0180
3,AMC Rebel SST,16.0,8.0,304.0,150.0,3433,12.0,70,US,7468.49,7468.4915
4,Ford Torino,17.0,8.0,302.0,140.0,3449,10.5,70,US,7503.30,7503.2995
...,...,...,...,...,...,...,...,...,...,...,...
401,Ford Mustang GL,27.0,4.0,140.0,86.0,2790,15.6,82,US,6069.64,6069.6450
402,Volkswagen Pickup,44.0,4.0,97.0,52.0,2130,24.6,82,Europe,4633.81,4633.8150
403,Dodge Rampage,32.0,4.0,135.0,84.0,2295,11.6,82,US,4992.77,4992.7725
404,Ford Ranger,28.0,4.0,120.0,79.0,2625,18.6,82,US,5710.69,5710.6875
405,Chevy S-10,31.0,4.0,119.0,82.0,2720,19.4,82,US,5917.36,5917.3600

In [ ]:
# METHOD 1
a['a1']=a['a1'].apply(pipe2)
a

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin,a1
0,Chevrolet Chevelle Malibu,18.0,8.0,307.0,130.0,3504,12.0,70,US,7622.95
1,Buick Skylark 320,15.0,8.0,350.0,165.0,3693,11.5,70,US,8034.12
2,Plymouth Satellite,18.0,8.0,318.0,150.0,3436,NaN,70,US,7475.02
3,AMC Rebel SST,16.0,8.0,304.0,150.0,3433,12.0,70,US,7468.49
4,Ford Torino,17.0,8.0,302.0,140.0,3449,10.5,70,US,7503.30
...,...,...,...,...,...,...,...,...,...,...
401,Ford Mustang GL,27.0,4.0,140.0,86.0,2790,15.6,82,US,6069.64
402,Volkswagen Pickup,44.0,4.0,97.0,52.0,2130,24.6,82,Europe,4633.81
403,Dodge Rampage,32.0,4.0,135.0,84.0,2295,11.6,82,US,4992.77
404,Ford Ranger,28.0,4.0,120.0,79.0,2625,18.6,82,US,5710.69
405,Chevy S-10,31.0,4.0,119.0,82.0,2720,19.4,82,US,5917.36

In [ ]:
# METHOD 2 -->FUNCTION 1,2 THATS PIPE FUNCTION BENIFITS
a['pipe']=a['Weight'].pipe(pipe1).pipe(pipe2)
a

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin,pipe
0,Chevrolet Chevelle Malibu,18.0,8.0,307.0,130.0,3504,12.0,70,US,7622.95
1,Buick Skylark 320,15.0,8.0,350.0,165.0,3693,11.5,70,US,8034.12
2,Plymouth Satellite,18.0,8.0,318.0,150.0,3436,NaN,70,US,7475.02
3,AMC Rebel SST,16.0,8.0,304.0,150.0,3433,12.0,70,US,7468.49
4,Ford Torino,17.0,8.0,302.0,140.0,3449,10.5,70,US,7503.30
...,...,...,...,...,...,...,...,...,...,...
401,Ford Mustang GL,27.0,4.0,140.0,86.0,2790,15.6,82,US,6069.64
402,Volkswagen Pickup,44.0,4.0,97.0,52.0,2130,24.6,82,Europe,4633.81
403,Dodge Rampage,32.0,4.0,135.0,84.0,2295,11.6,82,US,4992.77
404,Ford Ranger,28.0,4.0,120.0,79.0,2625,18.6,82,US,5710.69
405,Chevy S-10,31.0,4.0,119.0,82.0,2720,19.4,82,US,5917.36