In [48]:
import pandas as pd

# 1.CONCAT

In [49]:
data1=pd.DataFrame([[1,11],[2,12]],columns=['A','B'])
data2=pd.DataFrame([[1,11],[2,12]],columns=['A','B'])

In [59]:
# SAME COLUMN-->MERGE
# NO SAME COLUMN-->NULL  
pd.concat([data1,data2])

   A   B
0  1  11
1  2  12
0  1  11
1  2  12

# 2.JOIN

In [53]:
data3=pd.DataFrame([[1,11],[2,12]],columns=['A','B'])

data4=pd.DataFrame([[1,11],[2,12]],columns=['D','B'])

In [ ]:
# SAME COLUMN --> ADD SUFFIX LEFT OR RIGHT TABLE
# NO SAME COLUMN --> MERGE
data3.join(data4,lsuffix='_left')

   A  B_left  D   B
0  1      11  1  11
1  2      12  2  12

In [ ]:
# SAME COLUMN --> ADD SUFFIX LEFT OR RIGHT TABLE
# NO SAME COLUMN --> MERGE
data3.join(data4,rsuffix='_left')

   A   B  D  B_left
0  1  11  1      11
1  2  12  2      12