In [1]:
import pandas as pd

In [8]:
p=pd.read_csv('data/p.csv')
p

  product_id    product_name     category  price
0       P001  Wireless Mouse  Electronics    899
1       P002        Keyboard  Electronics   2499
2       P003    Laptop Stand  Accessories   1499
3       P004      Power Bank  Accessories   1999
4       P005     Smart Watch    Wearables   4999

In [9]:
pt=pd.read_csv('data/pt.csv')
pt

,transaction_id,product_id,quantity,total_amount,payment_method,payment_status
0,T001,P001,2,1798,UPI,Success
1,T002,P002,1,2499,Credit Card,Success
2,T003,P003,1,1499,Debit Card,Pending
3,T004,P004,3,5997,UPI,Success
4,T005,P005,1,4999,Net Banking,Failed

In [38]:
pd.merge(p,pt,left_on='product_id',right_on='product_id',how='right')

,product_id,product_name,category,price,transaction_id,quantity,total_amount,payment_method,payment_status
0,P001,Wireless Mouse,Electronics,899,T001,2,1798,UPI,Success
1,P002,Keyboard,Electronics,2499,T002,1,2499,Credit Card,Success
2,P003,Laptop Stand,Accessories,1499,T003,1,1499,Debit Card,Pending
3,P004,Power Bank,Accessories,1999,T004,3,5997,UPI,Success
4,P005,Smart Watch,Wearables,4999,T005,1,4999,Net Banking,Failed

In [40]:
pd.merge(p,pt,left_on='product_id',right_on='product_id',how='inner')

,product_id,product_name,category,price,transaction_id,quantity,total_amount,payment_method,payment_status
0,P001,Wireless Mouse,Electronics,899,T001,2,1798,UPI,Success
1,P002,Keyboard,Electronics,2499,T002,1,2499,Credit Card,Success
2,P003,Laptop Stand,Accessories,1499,T003,1,1499,Debit Card,Pending
3,P004,Power Bank,Accessories,1999,T004,3,5997,UPI,Success
4,P005,Smart Watch,Wearables,4999,T005,1,4999,Net Banking,Failed

In [41]:
pd.merge(p,pt,left_on='product_id',right_on='product_id',how='outer')

,product_id,product_name,category,price,transaction_id,quantity,total_amount,payment_method,payment_status
0,P001,Wireless Mouse,Electronics,899,T001,2,1798,UPI,Success
1,P002,Keyboard,Electronics,2499,T002,1,2499,Credit Card,Success
2,P003,Laptop Stand,Accessories,1499,T003,1,1499,Debit Card,Pending
3,P004,Power Bank,Accessories,1999,T004,3,5997,UPI,Success
4,P005,Smart Watch,Wearables,4999,T005,1,4999,Net Banking,Failed